### ISSUE TITLE
zooming and multiple graphs

### ISSUE THREAD

**Issue by yvesjans** [vimeo/timeserieswidget#6] opened 2013-05-08 12:29 UTC
Love the added zooming option but having some issues when there are multiple graphs on one page:
- only possible to zoom on the last graph, on the other graphs the selection works but the zooming not
- when zooming on the last graph the other graphs render blank.

**Comment by Finkregh** [comment] 2013-05-13 14:01
:+1:

**Comment by Dieterbe** [comment] 2013-05-13 22:11
hmm. confirmed. just wondering are you guys using graph explorer too?

**Comment by Finkregh** [comment] 2013-05-14 06:36
i might, but in another project :)

**Comment by yvesjans** [comment] 2013-05-14 10:05
same here :-) 

we use a custom dashboard that calls the graphite API (png)

**Comment by yvesjans** [comment] 2013-05-14 14:00
tried graph explorer, same issue on zooming

**Comment by GermanG** [comment] 2013-08-21 12:00
I can reproduce it using timeserieswidget only. It zooms using the last graph, using the same scale, no idea where the problem is  :(

UPDATE: got a clue at http://osdir.com/ml/flot-graphs/2012-04/msg00066.html 
Leaving this link here for future reference, I'll try to come up with a solution, but not soon

**Comment by Dieterbe** [comment] 2014-04-30 15:51
this is now fixed!

**Closed as completed by Dieterbe** 2014-04-30 15:51 UTC
